"""Independent contract tests for regression behavior and model metrics."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from numpy.testing import assert_allclose

from src.analysis import mae_to_accuracy, run_regression_analysis
from src.data_loader import load_and_clean_data
from src.output import rank_models


def _linear_data(n: int = 30) -> pd.DataFrame:
    temperature = np.linspace(0.0, 29.0, n)
    return pd.DataFrame({"temperature": temperature, "scoops": 2.0 * temperature})


@pytest.mark.parametrize(
    "model_id",
    [
        "poly1_intercept",
        "poly1_no_intercept",
        "poly2_intercept",
        "poly2_no_intercept",
        "poly3_intercept",
        "poly3_no_intercept",
        "spline_intercept",
        "spline_no_intercept",
    ],
)
def test_each_supported_model_produces_complete_finite_metrics(model_id):
    """Each documented model must fit, validate, and predict on numeric input."""
    data = _linear_data()

    result = run_regression_analysis(
        data,
        "temperature",
        "scoops",
        models=[model_id],
        prediction_temperature=40.0,
        cv_folds=5,
    )

    model = result.model_results[model_id]
    assert len(model.fold_rmse) == 5
    assert len(model.fold_accuracy) == 5
    assert np.isfinite(
        [
            model.train_rmse,
            model.bic,
            model.cv_rmse_mean,
            model.cv_rmse_std,
            model.cv_accuracy_mean,
            model.cv_accuracy_std,
            model.prediction_at_target,
        ]
    ).all()
    assert np.asarray(model.fold_accuracy).min() > 0.0
    assert np.asarray(model.fold_accuracy).max() <= 1.0


@pytest.mark.parametrize(
    ("model_id", "generator"),
    [
        ("poly1_intercept", lambda x: 3.0 * x + 4.0),
        ("poly1_no_intercept", lambda x: 3.0 * x),
        ("poly2_intercept", lambda x: 0.5 * x**2 + 3.0 * x + 4.0),
        ("poly2_no_intercept", lambda x: 0.5 * x**2 + 3.0 * x),
        ("poly3_intercept", lambda x: 0.1 * x**3 + 0.5 * x**2 + 3.0 * x + 4.0),
        ("poly3_no_intercept", lambda x: 0.1 * x**3 + 0.5 * x**2 + 3.0 * x),
    ],
)
def test_polynomial_models_recover_their_matching_synthetic_relationship(model_id, generator):
    """A polynomial model should exactly recover data generated by its own basis."""
    temperature = np.linspace(-3.0, 3.0, 30)
    data = pd.DataFrame({"temperature": temperature, "scoops": generator(temperature)})

    result = run_regression_analysis(
        data,
        "temperature",
        "scoops",
        models=[model_id],
        prediction_temperature=2.5,
        cv_folds=5,
    )

    model = result.model_results[model_id]
    assert model.train_rmse < 1e-10
    assert_allclose(model.prediction_at_target, generator(2.5), atol=1e-10)


def test_analysis_does_not_modify_the_caller_dataframe():
    """Analysis must preserve the original cleaned data supplied by its caller."""
    data = _linear_data()
    original = data.copy(deep=True)

    run_regression_analysis(data, "temperature", "scoops", cv_folds=5)

    pd.testing.assert_frame_equal(data, original)


def test_mae_accuracy_has_defined_bounds_and_known_values():
    """Held-out accuracy must be one for zero error and decrease with MAE."""
    assert_allclose(mae_to_accuracy(0.0), 1.0)
    assert_allclose(mae_to_accuracy(1.0), 0.5)
    assert_allclose(mae_to_accuracy(3.0), 0.25)


@pytest.mark.parametrize("cv_folds", [0, 1])
def test_analysis_rejects_fewer_than_two_cross_validation_folds(cv_folds):
    """Cross-validation requires at least two held-out partitions."""
    with pytest.raises(ValueError, match="at least 2"):
        run_regression_analysis(_linear_data(), "temperature", "scoops", cv_folds=cv_folds)


def test_analysis_allows_exactly_one_held_out_row_per_fold():
    """The boundary case of rows equal to folds must produce one metric per row."""
    data = _linear_data(n=5)

    result = run_regression_analysis(
        data,
        "temperature",
        "scoops",
        models=["poly1_intercept"],
        cv_folds=5,
    )

    assert len(result.model_results["poly1_intercept"].fold_rmse) == len(data)


def test_loader_preserves_zero_target_values(tmp_path):
    """Zero is a physically possible count and must not be removed as negative."""
    csv_path = tmp_path / "zero-count.csv"
    pd.DataFrame(
        {"temperature": [0.0, 10.0, 20.0], "scoops": [0.0, 1.0, -0.1]}
    ).to_csv(csv_path, index=False)

    result = load_and_clean_data(str(csv_path), "temperature", "scoops")

    assert result.rows_out == 2
    assert_allclose(result.data["scoops"].to_numpy(), [0.0, 1.0])


def test_ranking_handles_identical_metrics_without_nonfinite_scores():
    """Constant data must remain rankable when normalized metrics are tied."""
    temperature = np.linspace(0.0, 10.0, 20)
    data = pd.DataFrame({"temperature": temperature, "scoops": np.full(20, 2.5)})
    analysis = run_regression_analysis(
        data,
        "temperature",
        "scoops",
        models=["poly1_intercept", "poly2_intercept"],
        cv_folds=5,
    )

    ranking = rank_models(analysis)

    assert np.isfinite(ranking.ranking_table["weighted_score"]).all()
    assert ranking.best_model_id in {"poly1_intercept", "poly2_intercept"}